### ISSUE TITLE
Opening a 2nd time doesn't work on iPhone Browsers

### ISSUE THREAD

**Issue by phreak** [artberri/sidr#53] opened 2013-08-12 14:49 UTC
Sidr refuses to open the side panel when it was opened and closed once before (no reloads of the page, if you reload it works again but just once). That's though an issue as people tend to check the side navigation and may decide later to open it again from the same page. Interestingly it doesn't work just on iOS, tested under iPhone4 and 5 with Chrome and Safari.

I'm using an :hover image (different coloer) which shows, that shows that the toggle is still "open" after closing. When tested on Firefox Desktop with iPhone 3.0 User Agent, it works without a problem. Also on Samsung Galaxy under Android.

Anyone else experiencing the same?

**Comment by artberri** [comment] 2016-01-10 01:06
Can't reproduce the error now so I'm closing it

**Closed by artberri** 2016-01-10 01:06 UTC
Labels: bug

**Comment by goodniceweb** [comment] 2017-09-06 23:43
@artberri I got the same error on iOS 10.3
jquery 1.11.1
sidr 2.2.1

**Comment by artberri** [comment] 2017-12-08 15:36
Still not able to reproduce it.

Stackoverflow is a better place for doubts and implementation issues (don't forget to provide your failing code).
